/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as NekretnineRouteImport } from './routes/nekretnine'
import { Route as OglasiteNekretninuRouteImport } from './routes/oglasite-nekretninu'
import { Route as PoredjenjeRouteImport } from './routes/poredjenje'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as NekretnineIndexRouteImport } from './routes/nekretnine.index'
import { Route as NekretnineSlugRouteImport } from './routes/nekretnine.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const NekretnineRoute = NekretnineRouteImport.update({
  id: '/nekretnine',
  path: '/nekretnine',
  getParentRoute: () => rootRouteImport,
} as any)
const OglasiteNekretninuRoute = OglasiteNekretninuRouteImport.update({
  id: '/oglasite-nekretninu',
  path: '/oglasite-nekretninu',
  getParentRoute: () => rootRouteImport,
} as any)
const PoredjenjeRoute = PoredjenjeRouteImport.update({
  id: '/poredjenje',
  path: '/poredjenje',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const NekretnineIndexRoute = NekretnineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NekretnineRoute,
} as any)
const NekretnineSlugRoute = NekretnineSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NekretnineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/nekretnine': typeof NekretnineRouteWithChildren
  '/oglasite-nekretninu': typeof OglasiteNekretninuRoute
  '/poredjenje': typeof PoredjenjeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/nekretnine/$slug': typeof NekretnineSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/nekretnine/': typeof NekretnineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/oglasite-nekretninu': typeof OglasiteNekretninuRoute
  '/poredjenje': typeof PoredjenjeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/nekretnine/$slug': typeof NekretnineSlugRoute
  '/blog': typeof BlogIndexRoute
  '/nekretnine': typeof NekretnineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/nekretnine': typeof NekretnineRouteWithChildren
  '/oglasite-nekretninu': typeof OglasiteNekretninuRoute
  '/poredjenje': typeof PoredjenjeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/nekretnine/$slug': typeof NekretnineSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/nekretnine/': typeof NekretnineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/kontakt'
    | '/nekretnine'
    | '/oglasite-nekretninu'
    | '/poredjenje'
    | '/blog/$slug'
    | '/nekretnine/$slug'
    | '/blog/'
    | '/nekretnine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/oglasite-nekretninu'
    | '/poredjenje'
    | '/blog/$slug'
    | '/nekretnine/$slug'
    | '/blog'
    | '/nekretnine'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/kontakt'
    | '/nekretnine'
    | '/oglasite-nekretninu'
    | '/poredjenje'
    | '/blog/$slug'
    | '/nekretnine/$slug'
    | '/blog/'
    | '/nekretnine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  NekretnineRoute: typeof NekretnineRouteWithChildren
  OglasiteNekretninuRoute: typeof OglasiteNekretninuRoute
  PoredjenjeRoute: typeof PoredjenjeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nekretnine': {
      id: '/nekretnine'
      path: '/nekretnine'
      fullPath: '/nekretnine'
      preLoaderRoute: typeof NekretnineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oglasite-nekretninu': {
      id: '/oglasite-nekretninu'
      path: '/oglasite-nekretninu'
      fullPath: '/oglasite-nekretninu'
      preLoaderRoute: typeof OglasiteNekretninuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poredjenje': {
      id: '/poredjenje'
      path: '/poredjenje'
      fullPath: '/poredjenje'
      preLoaderRoute: typeof PoredjenjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/nekretnine/': {
      id: '/nekretnine/'
      path: '/'
      fullPath: '/nekretnine/'
      preLoaderRoute: typeof NekretnineIndexRouteImport
      parentRoute: typeof NekretnineRoute
    }
    '/nekretnine/$slug': {
      id: '/nekretnine/$slug'
      path: '/$slug'
      fullPath: '/nekretnine/$slug'
      preLoaderRoute: typeof NekretnineSlugRouteImport
      parentRoute: typeof NekretnineRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface NekretnineRouteChildren {
  NekretnineSlugRoute: typeof NekretnineSlugRoute
  NekretnineIndexRoute: typeof NekretnineIndexRoute
}

const NekretnineRouteChildren: NekretnineRouteChildren = {
  NekretnineSlugRoute: NekretnineSlugRoute,
  NekretnineIndexRoute: NekretnineIndexRoute,
}

const NekretnineRouteWithChildren = NekretnineRoute._addFileChildren(
  NekretnineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  KontaktRoute: KontaktRoute,
  NekretnineRoute: NekretnineRouteWithChildren,
  OglasiteNekretninuRoute: OglasiteNekretninuRoute,
  PoredjenjeRoute: PoredjenjeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
